module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  devel_generate: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  image: 0
  inline_form_errors: 0
  language: 0
  link: 0
  mailsystem: 0
  manage_display_fix_title: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  mimemail: 0
  monolog: 0
  node: 0
  onlyone: 0
  onlyone_admin_toolbar: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  permissions_filter: 0
  quickedit: 0
  settings_tray: 0
  simple_sitemap: 0
  smtp: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  manage_display: 1
  pathauto: 1
  views: 10
  minimal: 1000
  eu_cookie_compliance: 1001
theme:
  seven: 0
  adminimal_theme: 0
  stable: 0
  classy: 0
  olivero: 0
profile: minimal
